### ISSUE TITLE
String could not be parsed as XML

### ISSUE THREAD

**Issue by rvarbanov** [mrmarkfrench/silverpop-php-connector#20] opened 2015-08-14 14:34 UTC
Hi,

When I try to authenticate with XML I get this error:

```
String could not be parsed as XML
1.  SimpleXMLElement->__construct() in SilverpopIntegration/vendor/mrmarkfrench/silverpop-php-connector/src/SilverpopConnector/SilverpopXmlConnector.php at line 743
2.  SilverpopConnector\SilverpopXmlConnector->checkResponse() in SilverpopIntegration/vendor/mrmarkfrench/silverpop-php-connector/src/SilverpopConnector/SilverpopXmlConnector.php at line 140
3.  SilverpopConnector\SilverpopXmlConnector->authenticate() in SilverpopIntegration/vendor/mrmarkfrench/silverpop-php-connector/src/SilverpopConnector/SilverpopConnector.php at line 162
4.  SilverpopConnector\SilverpopConnector->authenticateXml() in SilverpopIntegration/Core.php at line 42
5.  SilverpopIntegration_Core->__construct() in SilverpopIntegration/XenForo/DataWriter/User.php at line 25
6.  SilverpopIntegration_XenForo_DataWriter_User->_postSave() in XenForo/DataWriter.php at line 1409
7.  XenForo_DataWriter->save() in SilverpopIntegration/XenForo/ControllerPublic/Account.php at line 50
8.  SilverpopIntegration_XenForo_ControllerPublic_Account->actionEmailPreferencesSave() in XenForo/FrontController.php at line 347
9.  XenForo_FrontController->dispatch() in XenForo/FrontController.php at line 134
10. XenForo_FrontController->run() in W:/var/www/html/www.xenforo.localhost/index.php at line 13
```

I spend a few hours trying to debug that but could not get anywhere. Do you have any clue what might be going wrong?

P.S. Ultimately I would like to use Rest, but when I do, I get an error with no error log...

**EDIT**: I did some more googling and found that the issue might be with my local install and how curl is making the calls to my baseURL. I was using HTTPS, and when I updated my baseURL to use HTTP, I am not getting the error anymore.

Do you know if I am not suing using HTTPS I will run into any issues?

**Comment by rvarbanov** [comment] 2015-08-18 20:20
Any idea if using http over https will break anything?
E.g. http://apiX.silverpop.com vs https://apiX.silverpop.com

**Comment by mrmarkfrench** [comment] 2015-08-19 19:11
@rvarbanov I wonder if the issue is in how your local environment is handling confirming the SSL certificate when you make the connection?

I don't know of a reason why using the HTTP address will break anything, but it has some obvious security implications when sending customer data (like email addresses) in the clear.

**Comment by rvarbanov** [comment] 2015-08-19 20:13
Thank you. I will soon be testing my work in a production environment and will let you know if that was just my localhost...

**Comment by MikkyX** [comment] 2015-12-22 23:52
I ran into this and I think it was a HTML entity issue - I ran my data through htmlentities() to tidy it up for use in XML and the problem went away.

**Comment by mrmarkfrench** [comment] 2020-09-02 19:09
Given that it's now been years with no further activity on this item, I'm going to close the issue. It sounds like @MikkyX has the solution with an HTML entity cleanup.

**Closed by mrmarkfrench** 2020-09-02 19:09 UTC
Labels: question
